config/routes.rb
Rails.application.routes.draw do
  
  
#ここから記載（たま）
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  #Public routes
  #public/homes
  namespace :public do 
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    #public/items
    resources :items, only: [:index, :show]
  
    # #public/customers
    get '/customers/my_page', to: 'customers#show', as: 'customer_my_page'
    get '/customers/information/edit', to: 'customers#edit', as: 'edit_customer_information'
    resources :items, only: [:index, :show] do #ジャンル検索ルート追加
     get 'items/search/:genre_id', to: 'items#search', as: 'search_public_items'
     end
    
    
    #public/customers
    patch '/customers/information', to: 'customers#update', as:  'update_customer_information'
    get '/customers/unsubscribe', to: 'customers#unsubscribe',as: 'customer_unsubscribe'
    patch '/customers/withdraw',to: 'customers#withdraw', as: 'customer_withdraw'
    
    #public/cart_items
    resources :cart_items, only: [:index, :update, :destroy, :create]do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
      end
    end
    #public/orders
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm', to: 'orders#confirm', as: 'confirm'
        get 'thanks', to: 'orders#thanks', as: 'thanks'
      end
    end
    #public/addresses
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  #Admin routes
  #admin/sessions
    namespace :admin do
    #resource :session, only: [:new, :create, :destroy], controller: 'sessions' do
    #  collection do
     #   get 'sign_in', action: :new
    #    post 'sign_in', action: :create
    #    delete 'sign_out', action: :destroy
    #  end
    #end
    #admin/homes
    root to: 'admin/homes#top'
    #admin/items
    resources :items
    #admin/genres
    resources :genres, only: [:index, :create, :edit, :update]
    #admin/customers
    resources :customers, only: [:index, :show, :edit, :update]
    #admin/orders
    resources :orders, only: [:show, :update, :index]
    #admin/order_details
    resources :order_details, only: [:update]
 end
  # root設定を最上位に追加
    root to: 'public/orders#new'
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  #アソシエーション
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  #first_name,last_name,postal_code,telephone_number,の欠損確認
  #郵便番号を7桁に指定、numericalityで数値であるか検証、only_integerで整数のみに制限
  #電話番号はnumericalityで数値であるか検証、only_integerで整数のみに制限
  #カタカナのみの入力に制限
  validates :last_name, :first_name, 
            :postal_code, :telephone_number,
            presence: true
  validates :postal_code, length: {is: 7}, numericality: {only_integer: true}
  validates :telephone_number, numericality: {only_integer: true}
  validates :first_name_kana, :last_name_kana,
  format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
    
  def full_name #フルネーム表示のため追加（おはる）
    last_name + '' + first_name
  end
  
  def full_name_kana #かなフルネーム表示のため追加（おはる）kanaの位置を修正(ひで)
    last_name_kana + '' + first_name_kana
  end
  
  def customer_status #会員ステータス追加（おはる）is_activeでfalseに修正(ひで)
    if is_active == false
      "退会"
    else
      "有効"
    end
  end
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    def index
        @customers = Customer.all
    end
    
    def show
        @customer = Customer.find(params[:id])
    end
   
    def edit
        @customer = Customer.find(params[:id])
    end
    
    def update
        @customer = Customer.find(params[:id])
        if @customer.update(customer_params)
            redirect_to admin_customer_path(@customer.id)
        else
            render "edit"
        end
    end
    
    private
    def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :postal_code, :telephone_number, :is_deleted)
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
  <h4><span style="background-color: #f8f9fa; padding: 0.25rem 0.75rem;"><%= (@customer.last_name + @customer.first_name) %>さんの会員情報編集</span></h4>

  <%= form_with model: @customer, url: admin_customer_path(@customer.id) do |f| %>
  <div class="row mb-1 mt-5">
    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">名前</label>
      <div class="col-sm-4">
        <div class="d-flex align-items-center">
          <%= f.text_field :last_name, value: @customer.last_name, autofocus: true, class: "form-control form-control-sm mr-3", placeholder: "姓" %>
          <%= f.text_field :first_name, value: @customer.first_name, autofocus: true, class: "form-control form-control-sm", placeholder: "名" %>
        </div>
      </div>
  </div>
        
  <div class="row mb-1">
    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">フリガナ</label>
      <div class="col-sm-4">
        <div class="d-flex align-items-center">
          <%= f.text_field :last_name_kana, value: @customer.last_name_kana, autofocus: true, class: "form-control form-control-sm mr-3", placeholder: "セイ" %>
          <%= f.text_field :first_name_kana, value: @customer.first_name_kana, autofocus: true, class: "form-control form-control-sm", placeholder: "メイ" %>
        </div>
      </div>
  </div>
  
  <div class="row mb-1">
    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">郵便番号</label>
      <div class="col-sm-4">
        <div class="d-flex align-items-center">
          <%= f.text_field :postal_code, value: @customer.postal_code, autofocus: true, class: "form-control form-control-sm mr-3" %>
        </div>
      </div>
  </div>
  
  <div class="row mb-1">
    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">住所</label>
      <div class="col-sm-4">
        <div class="d-flex align-items-center">
          <%= f.text_field :address, value: @customer.address, autofocus: true, class: "form-control form-control-sm mr-3" %>
        </div>
      </div>
  </div>
  
  <div class="row mb-1">
    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">電話番号</label>
      <div class="col-sm-4">
        <div class="d-flex align-items-center">
          <%= f.text_field :telephone_number, value: @customer.telephone_number, autofocus: true, class: "form-control form-control-sm mr-3" %>
        </div>
      </div>
  </div>
  
  <div class="row mb-1">
    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">メールアドレス</label>
      <div class="col-sm-4">
        <div class="d-flex align-items-center">
          <%= f.email_field :email, value: @customer.email, autofocus: true, class: "form-control form-control-sm mr-3" %>
        </div>
      </div>
  </div>
  
  <div class="row mb-1">
    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">会員ステータス</label>
      <div class="col-sm-4">
        <div class="d-flex align-items-center">
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効", { value: :false} %>
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "退会", { value: :true} %>
        </div>
      </div>
  </div>
                   
  <div class="row mb-1">
    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"></label>
      <div class="col-sm-4">
        <div class="d-flex align-items-center">
          <%= f.submit "編集内容を保存", class: 'btn btn-success' %>
        </div>
      </div>
  </div>
  <% end %>
  

app/views/admin/customers/index.html.erb
<div class="row align-items-center">
  <div class="col-auto">
    <h4 style="background-color: #f8f9fa; padding: 0.25rem 0.75rem;">会員一覧</h4>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to (customer.last_name + customer.first_name), admin_customer_path(customer.id) %></td>
        <td><%= customer.email %></td>
        <td><%= customer.customer_status %> </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/customers/show.html.erb
<div class="row align-items-center">
  <div class="col-auto">
    <h4 style="background-color: #f8f9fa; padding: 0.25rem 0.75rem;">
      <%= (@customer.last_name + @customer.first_name) %>さんの会員情報
    </h4>
  </div>
    <table class="table">
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <th>氏名</th>
        <td><%= @customer.last_name %><%= @customer.first_name %></td>
      </tr>
      <tr>
        <th>フリガナ</th>
        <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <th>郵便番号</th>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td><%= @customer.customer_status %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success" %></td>
        <td><%= link_to "注文履歴一覧を見る", admin_orders_path, class:"btn btn-primary" %></td> <!--パス追加-->
      </tr>
    </table>
</div>