config/routes.rb
Rails.application.routes.draw do
  
  
#ここから記載（たま）
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  #Public routes
  #public/homes
  namespace :public do 
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    #public/items
    resources :items, only: [:index, :show]
  
    # #public/customers
    get '/customers/my_page', to: 'customers#show', as: 'customer_my_page'
    get '/customers/information/edit', to: 'customers#edit', as: 'edit_customer_information'
    resources :items, only: [:index, :show] do #ジャンル検索ルート追加
     get 'items/search/:genre_id', to: 'items#search', as: 'search_public_items'
     end
    
    
    #public/customers
    patch '/customers/information', to: 'customers#update', as:  'update_customer_information'
    get '/customers/unsubscribe', to: 'customers#unsubscribe',as: 'customer_unsubscribe'
    patch '/customers/withdraw',to: 'customers#withdraw', as: 'customer_withdraw'
    
    #public/cart_items
    resources :cart_items, only: [:index, :update, :destroy, :create]do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
      end
    end
    #public/orders
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm', to: 'orders#confirm', as: 'confirm'
        get 'thanks', to: 'orders#thanks', as: 'thanks'
      end
    end
    #public/addresses
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  #Admin routes
  #admin/sessions
    namespace :admin do
    #resource :session, only: [:new, :create, :destroy], controller: 'sessions' do
    #  collection do
     #   get 'sign_in', action: :new
    #    post 'sign_in', action: :create
    #    delete 'sign_out', action: :destroy
    #  end
    #end
    #admin/homes
    root to: 'admin/homes#top'
    #admin/items
    resources :items
    #admin/genres
    resources :genres, only: [:index, :create, :edit, :update]
    #admin/customers
    resources :customers, only: [:index, :show, :edit, :update]
    #admin/orders
    resources :orders, only: [:show, :update, :index]
    #admin/order_details
    resources :order_details, only: [:update]
 end
  # root設定を最上位に追加
    root to: 'public/orders#new'
    
end

app/models/order.rb
class Order < ApplicationRecord
  
  #アソシエーション
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details
  
  #customer_id,address,name,shipping_cost,total_price,payment_method,の欠損確認
  #postal_codeは7文字に指定、numericalityで数値であるか検証、only_integerで整数のみに制限
	#shipping_cost,total_priceはnumericalityで数値であるか検証、only_integerで整数のみに制限
  validates :customer_id, :address,:name, :shipping_cost,
			  		:total_payment, :peyment_method,
			  		presence: true
	validates :postal_code, length: {is: 7}, numericality: {only_integer: true}
	validates :shipping_cost, :total_payment, numericality: {only_integer: true}
  
  #payment_methodカラムとstatusカラムに入る内容を記入
  enum peyment_method: {"クレジットカード" => 0,"銀行振込" => 1,}
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_shipment: 3, shipped: 4 }
  #order.order_address を使用できるようになります。
  def order_address
    "#{self.postal_code} #{self.address} #{self.name}"
  end
  # 住所と名前を分けました
  def postal_code_address_part
    "#{self.postal_code} #{self.address}"
  end

  def name_part
    self.name
  end
  
  # 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end
  
  def with_tax_total_payment
    (total_payment * 1.1).floor
  end
  
  
  ## 小計を求めるメソッド
  def subtotal
      item.with_tax_price * amount
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all
  end
    
  def show
    @shipping_cost = 800
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @customer = @order.customer
  end
    
    
  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
  if @order.status == "confirm_payment"
     @order_details.update_all(makings_status: :pending_production)
  end
    redirect_to admin_order_path(@order)
  end
      
   private
    
  def order_params
     params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="row align-items-center">
  <div class="col-auto">
    <h4 style="background-color: #f8f9fa; padding: 0.25rem 0.75rem;">注文履歴一覧</h4>
  </div>
    <table class="table">
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>　<!--必須機能ではない-->
      </tr>
      <% @orders.each do |order| %>
      <tr>
        <td><%= link_to admin_order_path(order) do %><%= order.created_at.strftime('%Y/%m/%d %H:%M') %><% end %></td> <!--詳細画面へ-->
        <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
        <td><%= order.order_details.sum(:amount) %></td>
        <td><%= order.status_i18n%></td>
      </tr>
      <% end %>
    </table>
</div>

app/views/admin/orders/show.html.erb
<h4><span style="background-color: #f8f9fa; padding: 0.25rem 0.75rem;">注文履歴詳細</span></h4>

<div class="row ml-2 mt-4">
  <table>
    <tr>
      <th width="200">購入者</th>
      <td>
        <%= link_to admin_customer_path(@order) do %>
          <%= @order.customer.last_name %><%= @order.customer.first_name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>注文日</th>
      <td>
        <%= @order.customer.created_at.strftime('%Y/%m/%d') %>
      </td>
    </tr>
    <tr>
      <th>配送先</th>
      <td>
        〒<%= @order.postal_code %>
        <%= @order.address %><br>
        <%= @order.name %>
      </td>
    </tr>
    <tr>
      <th>支払い方法</th>
      <td>
        <%= @order.peyment_method %>
      </td>
    </tr>
    <tr>
      <th>注文ステータス</th>
      <td>
        <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
          <%= f.select :status, Order.statuses.keys.map { |k| [I18n.t("enums.order.status.#{k}"), k] } %>
          <%= f.submit "更新", class: 'btn btn-primary' %>
        <% end %>
      </td>
    </tr>
  </table>
</div>
 
<div class="row mt-4">
   <div class="col-md-8">
      <table class=table>
         <thead>
           <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
           </tr>
         </thead>
         <% @order_details.each do |order_detail| %>
         <tbody>
          <tr>
           <td><%= order_detail.item.name %></td>
           <td><%= order_detail.with_tax_price.to_s(:delimited) %></td>
           <td><%= order_detail.amount %></td>
           <td><%= (order_detail.with_tax_price * order_detail.amount).floor.to_s(:delimited) %></td>
           <td><%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
                  <!--%= f.select :makings_status, ["着手不可", "製作待ち","製作中","製作確認"] %-->
                  <%= f.select :makings_status, OrderDetail.makings_statuses.keys.map {|k| [I18n.t("enums.order_detail.makings_status.#{k}"), k]} %>
                  <%= f.submit "更新", class: 'btn btn-primary' %>
               <% end %>
           </td>
          </tr>
         </tbody>
         <% end %>
       </table>
    </div>
 
    <div class="col-md-4 pl-3">
      <div>
         <p><strong>商品合計</strong>
         <%= @order.total_payment - @shipping_cost %> 円
         </p>
      </div>
      <div>
         <p><strong>送料</strong>
         <%= @shipping_cost %>円
         </p>
      </div>
      <div>
       <p><strong>請求金額合計</strong>
       <span class="text-dark font-weight-bold"><%= @order.total_payment %>円</span></p>
       </p>
      </div>
    </div>
   </div>
</div>
 
 
   
   
   