config/routes.rb
Rails.application.routes.draw do
  
  
#ここから記載（たま）
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  #Public routes
  #public/homes
  namespace :public do 
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    #public/items
    resources :items, only: [:index, :show]
  
    # #public/customers
    get '/customers/my_page', to: 'customers#show', as: 'customer_my_page'
    get '/customers/information/edit', to: 'customers#edit', as: 'edit_customer_information'
    resources :items, only: [:index, :show] do #ジャンル検索ルート追加
     get 'items/search/:genre_id', to: 'items#search', as: 'search_public_items'
     end
    
    
    #public/customers
    patch '/customers/information', to: 'customers#update', as:  'update_customer_information'
    get '/customers/unsubscribe', to: 'customers#unsubscribe',as: 'customer_unsubscribe'
    patch '/customers/withdraw',to: 'customers#withdraw', as: 'customer_withdraw'
    
    #public/cart_items
    resources :cart_items, only: [:index, :update, :destroy, :create]do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
      end
    end
    #public/orders
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm', to: 'orders#confirm', as: 'confirm'
        get 'thanks', to: 'orders#thanks', as: 'thanks'
      end
    end
    #public/addresses
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  #Admin routes
  #admin/sessions
    namespace :admin do
    #resource :session, only: [:new, :create, :destroy], controller: 'sessions' do
    #  collection do
     #   get 'sign_in', action: :new
    #    post 'sign_in', action: :create
    #    delete 'sign_out', action: :destroy
    #  end
    #end
    #admin/homes
    root to: 'admin/homes#top'
    #admin/items
    resources :items
    #admin/genres
    resources :genres, only: [:index, :create, :edit, :update]
    #admin/customers
    resources :customers, only: [:index, :show, :edit, :update]
    #admin/orders
    resources :orders, only: [:show, :update, :index]
    #admin/order_details
    resources :order_details, only: [:update]
 end
  # root設定を最上位に追加
    root to: 'public/orders#new'
    
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <p class="text-success"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p class="text-danger"><%= flash[:alert] %></p>
<% end %>
<% if flash[:success] %>
  <p class="text-success"><%= flash[:success] %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--Bootstrap CSS 追記-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
   
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!--css-->
    <link href="/assets/application.css" rel="stylesheet">
    
  </head>

  <body>
    <header>
       <nav class="navbar navbar-expand-lg navbar-dark bg-light-info">
          <div class="container">
            <%= link_to public_root_path do %>
            <%= image_tag "logo.png",size: "80x80" %>
            <% end %>
           <div class="collapse navbar-collapse">
              <!--管理者ログイン中ヘッダー画面-->
              <ul class = "navbar-nav ml-auto">
                <% if admin_signed_in? %>
                <li class="nav-item"><%= link_to '商品一覧',admin_items_path,class: 'btn btn-custom-pink btn-custom-white nav-link mr-3' %></li>
                <li class="nav-item"><%= link_to '会員一覧',admin_customers_path ,class: 'btn btn-custom-pink btn-custom-white nav-link mr-3'%></li>
                <li class="nav-item"><%= link_to '注文履歴一覧',admin_orders_path ,class: 'btn btn-custom-pink btn-custom-white nav-link mr-3'%></li>
                <li class="nav-item"><%= link_to 'ジャンル一覧',admin_genres_path ,class: 'btn btn-custom-pink btn-custom-white nav-link mr-3'%></li>
                <li class="nav-item"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'btn btn-custom-pink btn-custom-white nav-link mr-3' %></li>
                
              
              <!--顧客ログイン中ヘッダー画面-->
                <% elsif customer_signed_in? %>
                <li id="youkoso"  class="navbar-text">ようこそ、<%= current_customer.last_name %>さん！</li>
                <li class="nav-item"><%= link_to 'マイページ',public_customer_my_page_path ,class: 'btn btn-custom-pink btn-custom-white nav-link mr-3'%></li>
                <li class="nav-item"><%= link_to '商品一覧',public_items_path ,class: 'btn btn-custom-pink btn-custom-white nav-link mr-3'%></li>
                <li class="nav-item"><%= link_to 'カート',public_cart_items_path ,class: 'btn btn-custom-pink btn-custom-white nav-link mr-3'%></li>
                <li class="nav-item"><%= link_to 'ログアウト',destroy_customer_session_path, method: :delete ,class: 'btn btn-custom-pink btn-custom-white nav-link mr-3'%></li>
                
                <!--ログインしていない時ヘッダー画面-->
                <% else %>
               <li class="nav-item"><%= link_to 'About', public_about_path, class: 'btn btn-custom-pink btn-custom-white nav-link mr-3' %></li>
               <li class="nav-item"><%= link_to '商品一覧', public_items_path, class: 'btn btn-custom-pink btn-custom-white nav-link mr-3' %></li>
               <li class="nav-item"><%= link_to '新規登録', new_customer_registration_path, class: 'btn btn-custom-pink btn-custom-white nav-link mr-3' %></li>
               <li class="nav-item"><%= link_to 'ログイン', new_customer_session_path, class: 'btn btn-custom-pink btn-custom-white nav-link mr-3' %></li>
                <% end %>
              </ul>
           </div>
            
          </nav>
       </div>
    </header>
    <main>
      <div class="container">
        <%= render 'layouts/flash' %>
    <%= yield %>
      </div>
    </main>
    <!--foote-->
     <footer>
       <div class="container mt-5">
         <div class="row">
           <div class="mx-auto">
        		 　<p>© 2024 Enawata</p>
        	  </div>
        	</div>
       </div> 
     </footer>
    
  </body>
</html>